# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Arturia.ArturiaSoftwareCenter
PackageVersion: 2.4.5.760
Installers:
- InstallerUrl: https://dl.arturia.net/products/asc/soft/Arturia_Software_Center__2_4_5_760.exe
  Architecture: x86
  InstallerType: inno
  InstallerSha256: 09B3ECC1D975439F5862C0EC042C3A2B6DDC97F4AEB61B7271C7D5B21D048E1A
ManifestType: installer
ManifestVersion: 1.4.0
